DROP TABLE IF EXISTS history;
DROP TABLE IF EXISTS productConfig;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS category;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS credentials;



